version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace
      - ~/.config:/home/vscode/.host-config:ro
    command: sleep infinity
    user: vscode
    env_file: .env
