[default]
caseta_bridge_hostname = "caseta.run"
mqtt_hostname = "pihome.run"
mqtt_port = 8883


[devcontainer_pi_d]
  path_to_caseta_client_cert = "/host-home-folder/.config/pi-d/pylutron_caseta/caseta.run.crt"
  path_to_caseta_client_key = "/host-home-folder/.config/pi-d/pylutron_caseta/caseta.run.key"
  path_to_caseta_client_ca= "/host-home-folder/.config/pi-d/pylutron_caseta/caseta.run-bridge.crt"
  
  path_to_mqtt_client_cert =  "/host-home-folder/.config/pi-d/mqtt-ssl/client.crt"
  path_to_mqtt_client_key =  "/host-home-folder/.config/pi-d/mqtt-ssl/client.key"
  path_to_mqtt_client_ca =  "/host-home-folder/.config/pi-d/mqtt-ssl/pihome-ca.pem"
