[default]
# pylutron-caseta generates its own CA cert and uses it to generate
# and sign these client certs. These must be overridden and nonempty
path_to_caseta_client_cert = ""
path_to_caseta_client_key = ""
path_to_caseta_client_ca= ""


# users need to generate their own CA cert and use it to generate and sign
# these mqtt client certs. These must be overridden and nonempty
path_to_mqtt_client_cert = ""
path_to_mqtt_client_key = ""
path_to_mqtt_client_ca = ""
