name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set Up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
            
